### ISSUE TITLE
GitHub Pagesで公開について

### ISSUE THREAD

**Issue by aki77** [zengin-code/source-data#8]
こちらのリポジトリをGitHub Pagesで公開していただけると、以下のリポジトリのようにJSON APIとしても利用できて、非常に便利だと思うのですがいかがでしょうか。
ご検討よろしくお願いします。

https://github.com/morix1500/zengin

**Comment by rosylilly** [comment]
@aki77 いいご提案だなと思ったのですが source-data にその機能をもたせるのはちょっと違うな、と思ってしまったので github pages 用のリポジトリを用意しました。

https://zengin-code.github.io/

ご提案の通り JSON API としても簡単に機能するようにしてあります。

**Comment by aki77** [comment]
有難うございました！
便利に使わせていただきます。 👍
