### ISSUE TITLE
第四北越銀行（コード0140）が反映されていない

### ISSUE THREAD

**Issue by satonkmr** [zengin-code/source-data#9]
2020/1/8分の更新を反映してください。

http://ykaku.com/ginkokensaku/ment.html

> 2021年1月8日 | 第四銀行と北越銀行は合併し第四北越銀行になる

**Comment by rosylilly** [comment]
@satonkmr 67fe9794560ced14fcd832db06264890450eb4a6 にて反映済みです。お手元のデータを更新などしてご確認ください。

**Comment by satonkmr** [comment]
失礼いたしました！
手元データが更新されていないようでした。
